version: "3.0"
services:
  app:
    image: ghcr.io/djnotes/inspiration-bot:latest

    depends_on: 
      - db
  db:
    image: docker.io/library/mariadb:10.9.0
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_USER_FILE=env-mariadb-user
      - MARIDB_PASSWORD_FILE=env-mariadb-password
      - MARIADB_DATABASE_FILE=env-mariadb-database
    