version: "3.0"
services:
  app:
    image: ghcr.io/djnotes/inspiration-bot:main

    environment:
      - APP_CONF_FILE=env-app-conf
    

    depends_on: 
      - db
  db:
    image: docker.io/library/mariadb:10.7
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_USER_FILE=env-mariadb-user
      - MARIDB_PASSWORD_FILE=env-mariadb-password
      - MARIADB_DATABASE_FILE=env-mariadb-database

    
